package com.itpm.demoapi.demo.config

import com.itpm.demoapi.demo.model.Quote
import com.itpm.demoapi.demo.repository.QuoteRepository
import org.springframework.boot.ApplicationArguments
import org.springframework.boot.ApplicationRunner
import org.springframework.stereotype.Component

@Component
class QuoteDataInitializer(private val quoteRepository: QuoteRepository) : ApplicationRunner {
    override fun run(args: ApplicationArguments?) {
        if (quoteRepository.count() < 100) {
            val quotes = listOf(
                Quote(text = "The best way to get started is to quit talking and begin doing."),
                Quote(text = "Don't let yesterday take up too much of today."),
                Quote(text = "It's not whether you get knocked down, it's whether you get up."),
                Quote(text = "If you are working on something exciting, it will keep you motivated."),
                Quote(text = "Success is not in what you have, but who you are."),
                Quote(text = "The harder you work for something, the greater you'll feel when you achieve it."),
                Quote(text = "Dream bigger. Do bigger."),
                Quote(text = "Don't watch the clock; do what it does. Keep going."),
                Quote(text = "Great things never come from comfort zones."),
                Quote(text = "Push yourself, because no one else is going to do it for you."),
                Quote(text = "Success doesn't just find you. You have to go out and get it."),
                Quote(text = "The key to success is to focus on goals, not obstacles."),
                Quote(text = "Dream it. Wish it. Do it."),
                Quote(text = "Sometimes later becomes never. Do it now."),
                Quote(text = "Little things make big days."),
                Quote(text = "Don't stop when you're tired. Stop when you're done."),
                Quote(text = "Wake up with determination. Go to bed with satisfaction."),
                Quote(text = "Do something today that your future self will thank you for."),
                Quote(text = "It's going to be hard, but hard does not mean impossible."),
                Quote(text = "Don't wait for opportunity. Create it."),
                Quote(text = "Sometimes we're tested not to show our weaknesses, but to discover our strengths."),
                Quote(text = "The only limit to our realization of tomorrow is our doubts of today."),
                Quote(text = "Creativity is intelligence having fun."),
                Quote(text = "To see what is right and not do it is a lack of courage."),
                Quote(text = "Reading is to the mind, as exercise is to the body."),
                Quote(text = "The future belongs to those who believe in the beauty of their dreams."),
                Quote(text = "The only way to do great work is to love what you do."),
                Quote(text = "The purpose of our lives is to be happy."),
                Quote(text = "Life is what happens when you're busy making other plans."),
                Quote(text = "Get busy living or get busy dying."),
                Quote(text = "You only live once, but if you do it right, once is enough."),
                Quote(text = "Many of life's failures are people who did not realize how close they were to success when they gave up."),
                Quote(text = "If you want to live a happy life, tie it to a goal, not to people or things."),
                Quote(text = "Never let the fear of striking out keep you from playing the game."),
                Quote(text = "Money and success don't change people; they merely amplify what is already there."),
                Quote(text = "Your time is limited, so don't waste it living someone else's life."),
                Quote(text = "Not how long, but how well you have lived is the main thing."),
                Quote(text = "If life were predictable it would cease to be life, and be without flavor."),
                Quote(text = "The whole secret of a successful life is to find out what is one's destiny to do, and then do it."),
                Quote(text = "In order to write about life first you must live it."),
                Quote(text = "The big lesson in life, baby, is never be scared of anyone or anything."),
                Quote(text = "Curiosity about life in all of its aspects, I think, is still the secret of great creative people."),
                Quote(text = "Life is not a problem to be solved, but a reality to be experienced."),
                Quote(text = "The unexamined life is not worth living."),
                Quote(text = "Turn your wounds into wisdom."),
                Quote(text = "The way I see it, if you want the rainbow, you gotta put up with the rain."),
                Quote(text = "Do all the good you can, for all the people you can, in all the ways you can, as long as you can."),
                Quote(text = "Don't settle for what life gives you; make life better and build something."),
                Quote(text = "Everything negative – pressure, challenges – is all an opportunity for me to rise."),
                Quote(text = "I like criticism. It makes you strong."),
                Quote(text = "You never really learn much from hearing yourself speak."),
                Quote(text = "Life imposes things on you that you can't control, but you still have the choice of how you're going to live through this."),
                Quote(text = "Life is never easy. There is work to be done and obligations to be met—obligations to truth, to justice, and to liberty."),
                Quote(text = "Live for each second without hesitation."),
                Quote(text = "Life is like riding a bicycle. To keep your balance, you must keep moving."),
                Quote(text = "Life is really simple, but we insist on making it complicated."),
                Quote(text = "Life is a succession of lessons which must be lived to be understood."),
                Quote(text = "My mama always said, life is like a box of chocolates. You never know what you're gonna get."),
                Quote(text = "Keep calm and carry on."),
                Quote(text = "Maybe that's what life is... a wink of the eye and winking stars."),
                Quote(text = "Life is a long lesson in humility."),
                Quote(text = "In three words I can sum up everything I've learned about life: it goes on."),
                Quote(text = "Love the life you live. Live the life you love."),
                Quote(text = "Life is made of ever so many partings welded together."),
                Quote(text = "Life is trying things to see if they work."),
                Quote(text = "The healthiest response to life is joy."),
                Quote(text = "Life is short, and it is up to you to make it sweet."),
                Quote(text = "The longer I live, the more beautiful life becomes."),
                Quote(text = "Every moment is a fresh beginning."),
                Quote(text = "When you cease to dream you cease to live."),
                Quote(text = "If you spend your whole life waiting for the storm, you'll never enjoy the sunshine."),
                Quote(text = "Don't cry because it's over, smile because it happened."),
                Quote(text = "If you can do what you do best and be happy, you're further along in life than most people."),
                Quote(text = "We should remember that just as a positive outlook on life can promote good health, so can everyday acts of kindness."),
                Quote(text = "The best way to predict your future is to create it."),
                Quote(text = "You must expect great things of yourself before you can do them."),
                Quote(text = "Motivation is what gets you started. Habit is what keeps you going."),
                Quote(text = "People who are crazy enough to think they can change the world, are the ones who do."),
                Quote(text = "Try not to become a man of success, but rather become a man of value."),
                Quote(text = "Never give up. Great things take time. Be patient."),
                Quote(text = "Don't be afraid to give up the good to go for the great."),
                Quote(text = "If you cannot do great things, do small things in a great way."),
                Quote(text = "Success is not how high you have climbed, but how you make a positive difference to the world."),
                Quote(text = "What you get by achieving your goals is not as important as what you become by achieving your goals."),
                Quote(text = "The only place where success comes before work is in the dictionary."),
                Quote(text = "Happiness is not something ready made. It comes from your own actions."),
                Quote(text = "Opportunities don't happen. You create them."),
                Quote(text = "Don't be pushed around by the fears in your mind. Be led by the dreams in your heart."),
                Quote(text = "Work hard in silence, let your success be your noise."),
                Quote(text = "Doubt kills more dreams than failure ever will."),
                Quote(text = "The only thing standing between you and your goal is the story you keep telling yourself as to why you can't achieve it."),
                Quote(text = "The only way to achieve the impossible is to believe it is possible."),
                Quote(text = "Act as if what you do makes a difference. It does."),
                Quote(text = "Success is not the key to happiness. Happiness is the key to success."),
                Quote(text = "Never bend your head. Always hold it high. Look the world straight in the eye."),
                Quote(text = "What lies behind us and what lies before us are tiny matters compared to what lies within us.")
            )
            quoteRepository.saveAll(quotes)
        }
    }
} 